env:
  test: aa
hbase:
  url: http://trackagent:8090/device/track
  
spring:
  mvc:
    servlet:
      load-on-startup: 1
logging:
  file: ${spring.application.name}.log
  level:
    root: error
eureka:
  #client:
    #service-url:
      #defaultZone: http://192.168.10.237:48761/eureka
  #instance:
    #prefer-ip-address: true
    #ip-address: 47.97.71.240
    #instance-id: 47.97.71.240:${server.port}
  instance:
    ip-address: 192.168.10.237 #决定Eureka服务显示host
    hostname: ${eureka.instance.ip-address} #决定服务跳转host，必须指定
    prefer-ip-address: true #不设可自己指定，false会自动获取本地ipv4地址
    instance-id: ${eureka.instance.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.10.237:48761/eureka
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
info:
  version: 1.0-SNAPSHOT
  name: ${spring.application.name}